### ISSUE TITLE
Hide module namespace param and default to "env"

### ISSUE THREAD

**Issue by bhelx** [extism/dotnet-sdk#20]
For our host functions we allow people to set the module name / namespace. I think this is fine to expose but we should probably hide it because by default, most PDKs assume you will be using the "env" namespace on the guest side. Curious what you think @mhmd-azeez 

```csharp
HostFunction.FromMethod("kv_read", "env", IntPtr.Zero, (CurrentPlugin plugin, long keyOffset) =>
{
  // .. code   
})
```

See this discussion for more details on how we came to this conclusion: https://discord.com/channels/1011124058408112148/1050087490847002644/1160953757413146686

**Comment by mhmd-azeez** [comment]
Good point, i will add a `SetNamespace` method for HostFunction [similar to java](https://github.com/extism/java-sdk/blob/a0611e956f7c082c36304f8402f7b7844344a556/src/main/java/org/extism/sdk/HostFunction.java#L82)
