### ISSUE TITLE
Convert .NET strings to byte arrays internally to the plugin

### ISSUE THREAD

**Issue by ericsampson** [extism/dotnet-sdk#26]
In the .NET SDK examples, it makes it ergonomically painful to make the plugin consumer explicitly marshall inputs from .NET strings to bytes, and outputs from bytes back to .NET strings.

It feels like it would be preferable to have the .NET plugin code perform this automatically, in the most performant way (Spans etc)

**Comment by mhmd-azeez** [comment]
I agree, I am thinking of adding a new overload:
```csharp
string Call(string functionname, string input, CancellationToken ct)
```
