### ISSUE TITLE
Enable "warnings as errors"

### ISSUE THREAD

**Issue by ericsampson** [extism/dotnet-sdk#39]
I noticed that the code is currently not warning-clean.

It's a good idea to enable "warnings as errors" in order to help prevent bugs.

Cheers!!

<img width="708" alt="image" src="https://github.com/extism/dotnet-sdk/assets/1183853/0a12f17f-29e3-430a-ae2f-ca76e79a3420">

**Comment by mhmd-azeez** [comment]
Great idea @ericsampson, would you mind creating a PR for it? I'd be happy to help

**Comment by ericsampson** [comment]
That sounds a lot like my day job... lol
Realistically, it would probably be a long time for me to get around to it, if ever.
But I just wanted to record the FYI if nothing else :)

Cheers
