### ISSUE TITLE
Validate hash of Plugin code, if supplied

### ISSUE THREAD

**Issue by lukevp** [extism/dotnet-sdk#73]
The Go SDK uses `sha256` to validate the plugin code and ensure it has a matching hash, if a hash is supplied.

I assume the purpose of this is to provide a known-good hash when using the URL version, for example, to make sure that the plugin downloaded from the internet is the one that was expected when the code was written, and nothing has maliciously replaced that code.

Therefore, I think the current implementation is missing this protection around the hash.

I'm not sure if Extism internally uses the hash to validate the function code before executing it, but since I see [source in the Go SDK that validates the SHA](https://github.com/extism/go-sdk/blob/a6257adee32155a84ab8c6bf1b111e124cd51f12/extism.go#L403), it leads me to believe that this is implemented at the SDK level and not within Extism, but I could be wrong and there may be multiple levels of validation (and in that case, perhaps the Go SDK should be updated instead?)

**Comment by mhmd-azeez** [comment]
Hello @lukevp,

The .NET SDK is thin wrapper around the Rust SDK. This is where the hash is being checked in the Rust SDK:
https://github.com/extism/extism/blob/4e0cd3b1cf4c011facf6c0732524f270a65785a4/runtime/src/manifest.rs#L18

**Comment by lukevp** [comment]
Thanks for the clarification!
